### ISSUE TITLE
Neophyte - Not sure how to alternate openssl, num-bigint or rust-amp? 

### ISSUE THREAD

**Issue by FrankC01** [mikelodder7/accumulator-rs#1]
https://github.com/mikelodder7/accumulator-rs/blob/85be02651cba170d9ea49df34c455917f5a2b6f2/accumulator-common/src/lib.rs#L20

When I do a `cargo build` in the root of accumulator-rs I received a plethora of errors. I am new to rust and not sure how to indicate which implementation I want to build...

Can you shine a light on this?

**Comment by mikelodder7** [comment]
Hi @FrankC01, which OS are you on?
In order to run it with OpenSSL you will need to have it in your include path. If you want to us pure rust you can use 
`cargo build --no-default-features --features=bi-rust`

**Comment by FrankC01** [comment]
I am on MacOS and got it working using the options you provided. 

Thank you!
