### ISSUE TITLE
How did you get p and q from a Cunningham chain?

### ISSUE THREAD

**Issue by arthurgreef** [mikelodder7/accumulator-rs#5]
Hi you mention that p and q comes from a Cunningham chain. Can you tell me how you calculated that? I'd like to use a 64 bit modulus and i'm not sure how to get that from your Cunningham findings page.

Can you also tell me how you computed the generator and why?

Sorry for the junior questions. I tried to figure it out but I'm need help.

Thanks.

**Comment by mikelodder7** [comment]
Sure. I have a separate project for that that uses OpenSSL and GMP to calculate those

https://github.com/mikelodder7/cunningham_chain/blob/master/findings.md

**Comment by arthurgreef** [comment]
I saw that but where I do not see how these numbers are calculated from that page.
let p = BigInteger::from("132590288326793330806752358172617836030510421524323425886695490513600853466362871997907908739315399849138190997738786757721539635477379820932279026029679011350046717599386392663749253953274352000157227488895139775977945940993648470523136879899410690348931562489237825925601577159953591977449106730133820825719");
    let q = BigInteger::from("149253707427499607752440533538420296779167710000842829107795675900185486091323606384260179778233711456748787559527972657213022998726578510459854530854900733457277643303592216900588246498239579922221956281290954735600574251392801029419096160964874150455156365996536205549377586240264971604869515447059744740119");

**Comment by mikelodder7** [comment]
You can run the cunningham chain tool to generate those. `p` and `q` are just prime numbers so you can pick any of them.
